name: tdlabs
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 3.1.3+135

environment:
  sdk: ">=2.15.0 <3.16.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
  #for multi-language


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  animations: ^2.0.4
  animated_text_kit: ^4.2.1
  badges: ^2.0.1
  calendar_view: ^1.0.0
  carousel_slider: ^4.0.0
  camera: 0.9.4+18
  cupertino_icons: ^1.0.3
  country_pickers: ^2.0.0
  crypto: ^3.0.1
  dio: ^4.0.6
  device_info_plus: ^8.0.0
  email_validator: ^2.0.1
  email_launcher: ^1.1.1
  firebase_analytics: ^10.0.6
  firebase_core: ^2.3.0
  firebase_messaging: ^14.1.3
  firebase_dynamic_links: ^5.1.0
  file_picker: ^5.0.0
  fluttertoast: ^8.0.8
  flutter_local_notifications: ^9.0.0 
  flutter_cache_manager: ^3.3.0
  flutter_colorpicker: ^1.0.3
  flutter_social_button: ^1.1.4
  flutter_swipe_action_cell: ^2.1.2
  flutter_map: ^3.0.0
  google_sign_in: ^5.4.1
  get: ^4.6.1
  geocoding: ^2.0.5
  geolocator: ^9.0.1
  google_api_availability: ^3.0.1
  google_maps_flutter: ^2.5.0
  http: ^0.13.4
  intl: any
  image: ^3.1.3
  image_picker: ^0.8.5
  image_editor: ^1.0.2
  in_app_update: ^3.0.0
  lottie: ^1.2.2
  new_version: ^0.3.0
  map: any
  path_provider: ^2.0.9
  percent_indicator: 4.0.1
  permission_handler: 11.1.0
  share_plus: ^4.0.10+1
  shared_preferences: ^2.0.8
  store_redirect: ^2.0.1
  transition: ^2.0.2
  transparent_image: ^2.0.0
  uni_links: ^0.5.1
  url_launcher: ^6.1.5
  qr_flutter: ^4.0.0
  qr_code_scanner: ^1.0.0
  video_player: ^2.3.0
  video_compress: ^3.1.0
  webview_flutter: ^2.1.1
  map_launcher: ^2.4.0
  flutter_svg: ^1.0.3
  flutter_inappwebview: ^5.8.0
  firebase_auth: ^4.1.5
  firebase_installations: ^16.3.6
  flutter_polyline_points: ^1.0.0
  google_place: ^0.4.7
  address: ^0.1.0
  flutter_calendar_carousel: ^2.4.1
  facebook_app_events: ^0.18.3
  flutter_app_badger: ^1.5.0
  duration_picker: ^1.1.1
  health: any
  flutter_localization: 0.1.12
  syncfusion_flutter_charts: any
  syncfusion_flutter_pdfviewer: ^21.2.10
  flutter_datetime_picker_plus: ^2.0.1
  flutter_blue_plus: ^1.29.5

  flutter_easy_permission: ^1.1.2
  bluetooth_enable_fork: ^0.1.6
 
dependency_overrides:
  package_info_plus: ^4.0.1
  wakelock_windows: any
  win32: any
    
dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^1.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Montserrat     
      fonts:
        - asset: assets/fonts/Montserrat-Bold.ttf
        - asset: assets/fonts/Montserrat-Regular.ttf
        - asset: assets/fonts/Montserrat-SemiBold.ttf
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
