// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDlycJubTsIQs197f7opZuDdOgzA-J-I80',
    appId: '1:121089890526:android:9573795141aba62d2dca4f',
    messagingSenderId: '121089890526',
    projectId: 'buoyant-voyage-302308',
    storageBucket: 'buoyant-voyage-302308.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC68y_4HGV5ZilPhnJ0lZuSrc4Hc_yxngY',
    appId: '1:121089890526:ios:2a883facbd453d6f2dca4f',
    messagingSenderId: '121089890526',
    projectId: 'buoyant-voyage-302308',
    storageBucket: 'buoyant-voyage-302308.appspot.com',
    androidClientId: '121089890526-a90ag6o1ppq82lkgdjemucfft04rilmd.apps.googleusercontent.com',
    iosClientId: '121089890526-pfjue46rgge9sqg4uk4arf90ie9t1i24.apps.googleusercontent.com',
    iosBundleId: 'com.tedainternational.tdlabs',
  );
}
