// ignore_for_file: equal_keys_in_map

import 'package:get/get.dart';

class Language extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
        // 'en_US': {
        //   'About Us': 'About Us',`
        //   'Account Holder : ': 'Account Holder : ',
        //   'Account No : ': 'Account No : ',
        //   'Address : ': 'Address : ',
        //   'Address': 'Address',
        //   'Apply Promo Code': 'Apply Promo Code',
        //   'Apply': 'Apply',
        //   'Accept': 'Accept',
        //   'Appointment Date : ': 'Appointment Date : ',
        //   'Appointment Date: ': 'Appointment Date: ',
        //   'Appointment Date': 'Appointment Date',
        //   'Appointment By : ': 'Appointment By : ',
        //   'Appointment By: ': 'Appointment By: ',
        //   'Appointment By': 'Appointment By',
        //   'Answer': 'Answer',
        //   'Alert': 'Alert',
        //   'after you invite your friend using your referral code!':
        //       'after you invite your friend using your referral code!',
        //   'After the payment is successful, please send the payment proof by: ':
        //       'After the payment is successful, please send the payment proof by: ',
        //   'Add Test': 'Add Test',
        //   'Birthday': 'Birthday',
        //   'BILLING TO:': 'BILLING TO:',
        //   'By continuing, you cannot undo the action, the account will permanently deleted after approval from Tdlabs.':
        //       'By continuing, you cannot undo the action, the account will permanently deleted after approval from Tdlabs.',
        //   'City': 'City',
        //   'Confirm Decline Invitation?': 'Confirm Decline Invitation?',
        //   'Country': 'Country',
        //   'Contact Us': 'Contact Us',
        //   'Contact': 'Contact',
        //   'Change': 'Change',
        //   'Change To Email': 'Change To Email',
        //   'Change To Phone': 'Change To Phone',
        //   'Change Tdlabs ID': 'Change Tdlabs ID',
        //   'Cancel': 'Cancel',
        //   'Click here to watch instruction video':
        //       'Click here to watch instruction video',
        //   'Click here to view on map': 'Click here to view on map',
        //   'Confirm': 'Confirm',
        //   'Checkout': 'Checkout',
        //   'Checkout Confirmation': 'Checkout Confirmation',
        //   'Checkout Summary': 'Checkout Summary',
        //   'Current Details': 'Current Details',
        //   'Current action cannot be revert.':
        //       'Current action cannot be revert.',
        //   'Click here to submit your test result':
        //       'Click here to submit your test result',
        //   "Confirm submit the test result? Please recheck again before submit.":
        //       "Confirm submit the test result? Please recheck again before submit.",
        //   'Confirm Submit': 'Confirm Submit',
        //   'Current Location': 'Current Location',
        //   'Continue': 'Continue',
        //   'Check the "DETAILS" section to make sure all the details are correct. ':
        //       'Check the "DETAILS" section to make sure all the details are correct. ',
        //   'Choose your language': 'Choose your language',
        //   'Choose Available Voucher': 'Choose Available Voucher',
        //   'Change Password': 'Change Password',
        //   'Current Address': 'Current Address',
        //   'Current Home Address': 'Current Home Address',
        //   'Change Language': 'Change Language',
        //   'My Surveillance Status': 'My Surveillance Status',
        //   'Date: ': 'Date: ',
        //   'Date': 'Date',
        //   "Didn't get your PIN? ": "Didn't get your PIN? ",
        //   'Decline': 'Decline',
        //   'Discount': 'Discount',
        //   'Description': 'Description',
        //   'DETAILS: ': 'DETAILS: ',
        //   'Enter Promo Code': 'Enter Promo Code',
        //   'Empty list, pull to refresh.': 'Empty list, pull to refresh.',
        //   'Earn Commission': 'Earn Commission',
        //   'Enter New Tdlabs ID': 'Enter New Tdlabs ID',
        //   'Gender': 'Gender',
        //   'History': 'History',
        //   'have invited you.': 'have invited you.',
        //   'Invite Code ': 'Invite Code ',
        //   'Item': 'Item',
        //   'Info-IdChange':
        //       'This is your login ID, by changing your Tdlabs ID, your login ID will also change.',
        //   'Instructions': 'Instructions',
        //   'INSTRUCTIONS :': 'INSTRUCTIONS :',
        //   'info-sample-before-test':
        //       'Please make sure the result is clearly seen before submitting your result.',
        //   'info-sample':
        //       'Please take the picture with good lighting condition, and place the test-kit within the box provided.\n',
        //   'Logout': 'Logout',
        //   'Link-info':
        //       'Link is a feature to connect you to your company so that your company can arrange test for you. Start link with your company now!',
        //   'Latest News': 'Latest News',
        //   'linked with company': 'linked with company',
        //   'My Surveillance History': 'My Surveillance History',
        //   'Message': 'Message',
        //   'My new ID is an Email': 'My new ID is an Email',
        //   'My new ID is a phone number': 'My new ID is a phone number',
        //   'Name': 'Name',
        //   'Name : ': 'Name : ',
        //   'No, the result is Negative': 'No, the result is Negative',
        //   'No result found.': 'No result found.',
        //   'No result found, pull to refresh.':
        //       'No result found, pull to refresh.',
        //   'Nationality': 'Nationality',
        //   'Order History': 'Order History',
        //   'Our AI system detect the result as ':
        //       'Our AI system detect the result as ',
        //   'Phone Number': 'Phone Number',
        //   'Phone No. : ': 'Phone No. : ',
        //   'Postcode': 'Postcode',
        //   'Profile': 'Profile',
        //   'Payment': 'Payment',
        //   'Privacy Policy': 'Privacy Policy',
        //   'Price': 'Price',
        //   'Please complete your profile to proceed':
        //       'Please complete your profile to proceed',
        //   'Pay using bank transfer method to the account number listed in "TRANSFER TO" section with exact transfer details as shown.':
        //       'Pay using bank transfer method to the account number listed in "TRANSFER TO" section with exact transfer details as shown.',
        //   'Point of care : ': 'Point of care : ',
        //   'Point of Care: ': 'Point of Care: ',
        //   'Point of Care': 'Point of Care',
        //   'Point of care ': 'Point of care ',
        //   'Please take the picture with good lighting condition':
        //       'Please take the picture with good lighting condition',
        //   'Please key in the 6 digit PIN sent to your':
        //       'Please key in the 6 digit PIN sent to your',
        //   'Policy': 'Policy',
        //   'Please confirm the result.': 'Please confirm the result.',
        //   'Please upload your IC/Passport photo for verification purposes, your IC/Passport must be shown clearly in the photo':
        //       'Please upload your IC/Passport photo for verification purposes, your IC/Passport must be shown clearly in the photo',
        //   'Shipping & Refund Policy': 'Shipping & Refund Policy',
        //   'Shipping': 'Shipping',
        //   'skip-ai-info':
        //       'It seems our AI system having hard time detecting your self-test kit result, skip AI for manual verification?',
        //   'Referral': 'Referral',
        //   'Result Confirmation': 'Result Confirmation',
        //   'Request Delete Account': 'Request Delete Account',
        //   'Reference No: ': 'Reference No: ',
        //   'RESULT DETAILS :': 'RESULT DETAILS :',
        //   'registered mobile phone no.': 'registered mobile phone no.',
        //   'registered email': 'registered email',
        //   'Save': 'Save',
        //   'Self Test': 'Self Test',
        //   'Self-Test Kit Obtained From': 'Self-Test Kit Obtained From',
        //   'Submit': 'Submit',
        //   'Submit Test': 'Submit Test',
        //   'Submit to MySejahtera : ': 'Submit to MySejahtera : ',
        //   'Submitted date: ': 'Submitted date: ',
        //   'Session : ': 'Session : ',
        //   'Session': 'Session',
        //   'Self-Test Kits': 'Self-Test Kits',
        //   'Statistic': 'Statistic',
        //   'Street 1': 'Street 1',
        //   'Street 2': 'Street 2',
        //   'Select Voucher / Promo Code ...': 'Select Voucher / Promo Code ...',
        //   'Scan a valid QR code to get Validation Report':
        //       'Scan a valid QR code to get Validation Report',
        //   'Specimen Type : ': 'Specimen Type : ',
        //   'Share Referral Code Now': 'Share Referral Code Now',
        //   'Shipping Details': 'Shipping Details',
        //   'Shipping fees': 'Shipping fees',
        //   'Session: ': 'Session: ',
        //   'State': 'State',
        //   'Submit your test result': 'Submit your test result',
        //   'States: ': 'States: ',
        //   'Select Type Of Test': 'Select Type Of Test',
        //   'Select Self Test Brand': 'Select Self Test Brand',
        //   'Select Point of Care': 'Select Point of Care',
        //   'Treat your friend a trial voucher appointment for their first time register using your code!':
        //       'Treat your friend a trial voucher appointment for their first time register using your code!',
        //   'Type : ': 'Type : ',
        //   'Test Location : ': 'Test Location : ',
        //   'Type': 'Type',
        //   'Test': 'Test',
        //   "The result is 'Invalid'": "The result is 'Invalid'",
        //   'Total Payment': 'Total Payment',
        //   'Total Price': 'Total Price',
        //   'Type of Appointment': 'Type of Appointment',
        //   'Transfer Amount : ': 'Transfer Amount : ',
        //   'TEST IMAGE :': 'TEST IMAGE :',
        //   'Test Method:': 'Test Method:',
        //   'Type Of Report: ': 'Type Of Report: ',
        //   'TRANSFER TO:': 'TRANSFER TO:',
        //   'Transfer Details : ': 'Transfer Details : ',
        //   'Update Profile': 'Update Profile',
        //   'Upload Result Image': 'Upload Result Image',
        //   'Unlink from this company?': 'Unlink from this company?',
        //   'Verify Identification': 'Verify Identification',
        //   'Validated date: ': 'Validated date: ',
        //   'Validation Method': 'Validation Method',
        //   'Validation : ': 'Validation : ',
        //   'Voucher': 'Voucher',
        //   'Verify Phone Number': 'Verify Phone Number',
        //   'Verify Email': 'Verify Email',
        //   'Your Tdlabs ID': 'Your Tdlabs ID',
        //   'Your test location': 'Your test location',
        //   'Yes, the result is Negative': 'Yes, the result is Negative',
        //   'Yes, the result is Positive': 'Yes, the result is Positive',
        //   "Yes, the result is 'Invalid'": "Yes, the result is 'Invalid'",
        // }, //todo::Bahasa Malaysia Translate
        'ms_MY': {
          //add by 30112022
          'About Us': 'Tentang Kami',
          'Rewards': 'Ganjaran',
          'Smart Consuming Programme': 'Program Smart Consuming',
          'Proof of Test': 'Pembuktian Saringan',
          'Change Profile Picture': 'Tukar Gambar Profil',
          'Select Picture': 'Pilih Gambar',
          'Remove Picture': 'Keluarkan Gambar',
          'Back': 'Kembali',
          'My Wallet': 'Wallet Saya',
          'Wallet': 'Wallet',
          'Reward History': 'Rekod Ganjaran',
          'Reward Available Today': 'Ganjaran Anda Hari Ini',
          'Medical': 'Perubatan',
          'Directory': 'Direktori',
          'Covid-19 Screening': 'Saringan Covid-19',
          'Ask Doctor\n(Coming Soon)': 'Tanya Doktor (Akan Datang)',
          'Ask Doctor (Coming Soon)': 'Tanya Doktor (Akan Datang)',
          'Period Tracker\n(Coming Soon)': 'Period Tracker (Akan Datang)',
          'Period Tracker (Coming Soon)': 'Period Tracker (Akan Datang)',
          'Health Ledger': 'Rekod Kesihatan',
          'Medical Directory': 'Direktori Perubatan',
          'Categories': 'Kategori',
          'Clinics': 'Klinik',
          ' of ': ' dari ',
          'Clinics]': ' Klinik]',
          ' Pages': ' Muka Surat',
          'Cardiology (Heart Specialist)': 'Kardiologi (Pakar Jantung)',
          'Chiropractic (Spine Specialist)':
              'Kiropraktik (Pakar Tulang Belakang)',
          'Confinement Center': 'Pusat Berpantang',
          'Dermatology (Skin Specialist)': 'Dermatologi (Pakar Kulit)',
          'Fertility Clinics': 'Klinik Kesuburan',
          'Gastroenterology Hepatology (Digestive Sys. Spec)':
              'Gastroenterologi Hepatologi (Pakar Sistem Penghadaman)',
          'General Practitioner': 'Perubatan Am',
          'Haemodialysis Center (Blood Dialysis)':
              'Pusat Haemodialisis (Dialisis Darah)',
          'Health Screening': 'Pemeriksaan Kesihatan',
          'Maxillofacial (Dental Care)': 'Maksilofasial (Penjagaan Gigi)',
          'Medical Aesthetic': 'Perubatan Estetik',
          'Obstetrics Gynaecology (Reproductive Specialist)':
              'Obstetik Ginekologi (Pakar Pembidanan & Sakit Puan)',
          'Ophaltomology (Eye Specialist)': 'Ofaltomologi (Pakar Mata)',
          'Ortopaedic (Bone Specialist)': 'Ortopedik (Pakar Tulang)',
          'Otorhinolaryngology (Ear, Nose, Throat Specialist)':
              'Otohinolaringologi (Pakar Telinga, Hidung, Tekak)',
          'Physiotherapy': 'Fisioterapi',
          'Psychiatrist': 'Psikiatri',
          'Traditional Chinese Medicine Center':
              'Pusat Perubatan Tradisional Cina',
          'Wellness Section': 'Kesihatan Fizikal',
          'Registration No: ': 'No. Pendaftaran: ',
          'Email:': 'Emel:',
          'Email: ': 'Emel: ',
          'Address:': 'Alamat:',
          'Address: ': 'Alamat: ',
          'Description: ': 'Penerangan: ',
          'Expertise: ': 'Kepakaran: ',
          'Directions': 'Arah',
          'Contact': 'Hubungi',
          'Close': 'Tutup',
          'Book Appointment': 'Janji Temu',
          'Covid Screening': 'Saringan Covid',
          'Professional Validation(Fees Apply)':
              'Pengesahan Profesional (Caj Dikenakan)',
          'Type of Appointment:': 'Jenis Temu Janji',
          'Point of Care: ': 'Klinik Panel',
          'Price:': 'Harga:',
          'Free': 'Percuma',
          'Check Out': 'Daftar Keluar',
          'Type:': 'Jenis:  ',
          'Appointment Date :': 'Tarikh Temu Janji: ',
          'General Booking': 'Tempahan Umum',
          'Thank you for booking with TD-Labs':
              'Terima kasih kerana menempah bersama TD-Labs',
          'General Appointment': 'Temu Janji Umum',
          'Morning (8am - 10am)': 'Pagi (8am - 10am)',
          'Afternoon (2pm - 4pm)': 'Tengahari (2pm - 4pm)',
          'Evening (6pm - 8pm)': 'Petang (6pm - 8pm)',

          'Location:': 'Lokasi:',
          'Booking Successful': 'Tempahan Berjaya',
          'Welcome to Smart Keluarga': 'Selamat Datang ke Smart Keluarga',
          '1.Select nearest machine\n2.Select desired item\n3.Check out and Collect':
              '1.Pilih mesin terdekat\n2.Pilih produk\n3.Daftar Keluar & Ambil produk',
          'Select Vending Machine': 'Pilih Mesin Layan Diri',
          'Nearest Vending Machine based on your current location':
              'Mesin terdekat berdasarkan lokasi anda',
          'Nearest Vending Machine \nbased on your current location':
              'Mesin terdekat berdasarkan lokasi anda',
          'Normal Delivery': 'Penghantaran Normal',
          'Self Pickup': 'Ambil Sendiri',
          'Items': 'Produk',
          'Points': 'Poin',
          'Quantity': 'Kuantiti',
          'Buy Now': 'Beli Sekarang',
          'Email': 'Emel',
          'Call': 'Panggilan',
          'Same Day': 'Sama Hari',
          //add by 30112022
          'Account Holder : ': 'Pemegang Akaun :',
          'Account No : ': 'No Akaun :',
          'Active : ': 'Aktif: ',
          'Active': 'Aktif',
          'Add': 'Tambah',
          'Address : ': 'Alamat: ',
          'Address': 'Alamat',
          'Answer': 'Jawapan',
          'Accept': 'Terima',
          'Alert': 'Amaran',
          'Apply Promo Code': 'Terapkan Kod Promosi',
          'Apply': 'Terapkan',
          'Appointment Date : ': 'Tarikh Appointment :',
          'Appointment Date': 'Tarikh Appointment',
          'Appointment Date: ': 'Tarikh Appointment :',
          'Appointment By : ': 'Temujanji Dengan: ',
          'Appointment By': 'Temujanji Dengan',
          'Appointment By: ': 'Temujanji Dengan: ',
          'Add Test': 'Tambah Ujian',
          'Continue with the current self-test video?':
              'Sambung dengan video ujian kendiri ini?',
          'After the payment is successful, please send the payment proof by: ':
              'Setelah pembayaran berjaya, kirimkan bukti pembayaran menerusi:',
          'after you invite your friend using your referral code!':
              'setelah anda menjemput rakan anda menggunakan kod rujukan anda!',
          'Birthday': 'Tarikh Lahir',
          'BILLING TO:': 'BIL KE:',
          'By continuing, you cannot undo the action, the account will permanently deleted after approval from Tdlabs.':
              'Tindakan ini tidak boleh diundur setelah akaun anda dihapus oleh Tdlabs.',
          'Capture Picture of test kit and Upload Result\nPlease ensure that the result image is clear before submitting':
              'Tangkap Gambar kit ujian dan Muat Naik Hasil\nSila pastikan imej keputusan jelas sebelum menyerahkan',
          'City': 'Bandar',
          'Country': 'Negara',
          'Change': 'Tukar',
          'Choose Your Validation': 'Pilih Pengesahan Anda',
          'Change To Phone': 'Tukar ke Nombor Tel',
          'Confirm': 'Setuju',
          'Confirm Decline Invitation?': 'Sahkan tolak jemputan?',
          'Checkout': 'Daftar\nKeluar',
          'Checkout Confirmation': 'Pengesahan Bayaran',
          'Checkout Summary': 'Ringkasan Pembayaran',
          "Confirm Submit": 'Sahkan Hantar',
          'Click here to submit your test result':
              'Klik di sini untuk menghantar keputusan ujian anda',
          'Current action cannot be revert.':
              'Tindakan diambil tidak boleh dikembalikan',
          "Confirm submit the test result? Please recheck again before submit.":
              "Anda pasti dengan hasil ujian? Periksa kembali sebelum hantar.",
          'Contact Us': 'Hubungi Kami',
          'Contact': 'Hubungi',
          'Continue': 'Sambung',
          'Completed': 'Selesai',
          'Change To Email': 'Tukar ke Email',
          'Choose your language': 'Pilih Bahasa Anda',
          'Choose Available Voucher': 'Pilih baucar',
          'Change Password': 'Tukar Kata laluan',
          'Change Tdlabs ID': 'Tukar ID Tdlabs',
          'Continue Payment': 'Sambung Bayaran',
          'Cancel': 'Batal',
          'Current Address': 'Alamat Semasa',
          'Current Password': 'Kata Laluan Terkini',
          'Click Here To Watch Instruction Video':
              'Tekan untuk menonton video arahan',
          'Click here to view on map': 'Tekan untuk lihat di peta',
          'Current Details': 'Butiran Semasa',
          'Change Language': 'Tukar Bahasa',
          'Current Location': 'Lokasi Semasa',
          'Current Home Address': 'Alamat Semasa',
          'Check the "DETAILS" section to make sure all the details are correct. ':
              'Periksa bahagian "BUTIRAN" untuk memastikan semua perinciannya betul. ',
          'Discount : ': 'Diskaun :',
          'My Surveillance Status': 'Status Pengawasan Saya',
          'Date: ': 'Tarikh: ',
          'Date': 'Tarikh',
          'Decline': 'Tolak',
          "Didn't get your PIN? ": "Tidak menerima PIN? ",
          'Description': 'Penerangan',
          'DETAILS: ': 'BUTIRAN: ',
          'Discount': 'Diskaun',
          'Earn Commission': 'Dapatkan komisen',
          'Enter New Tdlabs ID': 'Isikan ID Tdlabs baru',
          'Empty list, pull to refresh.':
              'Senarai kosong, tarik untuk muat semula',
          'Enter Promo Code': 'Masukkan Kod Promo',
          'General Validation(Free)': 'Pengesahan Umum (Percuma)',
          'Free Consultation': 'Konsultasi Percuma',
          'Gender': 'Jantina',
          'History': 'Rekod',
          'Select Provider': 'Pilih Pembekal',
          'have invited you.': 'menjemput anda.',
          'IC/ Passport': 'No KP/Pasport',
          'Invite Code:  ': 'Kod Jemputan: ',
          'Item': 'Barang',
          'Instructions': 'Arahan',
          'info-sample-before-test':
              'Sila pastikan keputusan dapat dilihat dengan jelas sebelum menghantar keputusan anda.',
          'info-sample':
              'Sila ambil gambar dengan keadaan pencahayaan yang baik, dan letakkan kit ujian dalam kotak yang disediakan. \n',
          'INSTRUCTIONS :': 'ARAHAN :',
          'Item(s) Ordered: ': 'Pesanan Barang: ',
          'Logout': 'Keluar',
          'Info-IdChange':
              'Ini adalah ID log masuk anda, jika anda menukar Tdlabs ID anda, ID log masuk juga akan berubah.',
          'Link-info':
              'Pautan Korporat adalah fitur yang menghubungkan anda dan syarikat untuk memudahkan pengurusan ujian untuk anda. Mulakan pautan dengan syarikat anda sekarang!',
          'linked with company': 'sudah link dengan syarikat',
          'Latest News': 'Berita Terkini',
          'Last Update : ': 'Kemaskini Terakhir : ',
          'My Surveillance History': 'Rekod Pengawasan Saya',
          'Message': 'Mesej',
          'Medical': 'Perubatan',
          'My new ID is an Email': 'ID baru saya adalah Emel',
          'My new ID is a phone number': 'ID baru saya adalah nombor telefon',
          'Name': 'Nama',
          'Name : ': 'Nama : ',
          'New Password': 'Kata Laluan Baru',
          'No, the result is Negative': 'Tidak, hasil ujian adalah Negative',
          'No, the result is Positive': 'Tidak, hasil ujian adalah Positive',
          'No result found, pull to refresh.':
              'Hasil gagal ditemui, sila tarik untuk muat semula.',
          'Nationality': 'Warganegara',
          'Order History': 'Rekod Pesanan',
          'Order Item(s): ': 'Barang Pesanan: ',
          'No result found.': 'Hasil tidak ditemui',
          'Our AI system detect the result as ':
              'Sistem AI kami mengesan hasil ujian sebagai ',
          'Pending': 'Dalam Proses',
          'Phone No.': 'No. Telefon',
          'Phone No. : ': 'No. Telefon :',
          'Postcode': 'Poskod',
          'Profile': 'Profil',
          'Payment': 'Bayaran',
          'Payment By: ': 'Pembayaran: ',
          'Point of care : ': 'Klinik: ',
          'Please confirm the result.': 'Sila sahkan hasil ujian.',
          'Point of Care:': 'Klinik:',
          'Point of Care': 'Klinik',
          'Point of care ': 'Klinik ',
          'Point Of Care Selection': 'Pilih Klinik',
          'Privacy Policy': 'Dasar Privasi',
          'Shipping & Refund Policy': 'Dasar Hantaran & Pulangan',
          'Shipping fees': 'Caj penghantaran',
          'Policy': 'Polisi',
          'Proceed with payment\nSelf-Test report will be sent once ready':
              'Teruskan dengan Pembayaran\nLaporan Ujian Kendiri akan dihantar setelah siap',
          'Please upload your IC/Passport to continue':
              'Sila muat naik IC/Pasport anda untuk sambung',
          'Please take the picture with good lighting condition':
              'Sila ambil gambar dengan keadaan pencahayaan yang baik',
          'Please key in the 6 digit PIN sent to your':
              'Sila isi 6 digit PIN yang telah dihantar ke',
          'PAYMENT DETAILS: ': 'BUTIRAN PEMBAYARAN: ',
          'Please wait for': 'Sila tunggu selama',
          'We will proceed automatically':
              'Kami akan meneruskan secara automatik',
          'Please complete your profile to proceed':
              'Sila lengkapkan profil anda untuk sambung',
          'Pay using bank transfer method to the account number listed in "TRANSFER TO" section with exact transfer details as shown.':
              'Bayar menggunakan cara pemindahan bank kepada nombor akaun yang dipaparkan di bahagian “PINDAH KEPADA”  dengan jumlah pindahan yang dinyatakan',
          'Please upload your IC/Passport photo for verification purposes, your IC/Passport must be shown clearly in the photo':
              'Sila muat naik gambar IC / Pasport anda untuk tujuan pengesahan, IC / Pasport anda mesti ditunjukkan dengan jelas di dalam gambar',
          'Quantity': 'Kuantiti',
          'QR Scan': 'Imbas QR/Kod',
          'Referral': 'Rujukan',
          'RECEIPT :': 'RESIT :',
          'Request Delete Account': 'Permintaan Hapus Akaun',
          'Reference No: ': 'No Rujukan: ',
          'RESULT DETAILS :': 'BUTIRAN HASIL :',
          'Record your self-test video to continue':
              'Rakam video ujian kendiri untuk sambung',
          'registered mobile phone no.': 'nombor telefon yang telah didaftar',
          'registered email': 'emel yang telah didaftar',
          'Result Confirmation': 'Pengesahan Hasil Ujian',
          'skip-ai-info':
              'Sistem AI kami telah mengalami kesukaran untuk mengesan keputusan kit ujian kendiri anda, langkau pengesahan AI dan teruskan ke pengesahan manual?',
          'Self Test': 'Ujian Kendiri',
          'Submit': 'Hantar',
          'Submitted date: ': 'Tarikh Dihantar: ',
          'Submit to MySejahtera : ': 'Hantar ke MySejahtera : ',
          'Self-Test Kit Obtained From': 'Kit Ujian Kendiri Diperolehi Dari',
          'Session : ': 'Sesi : ',
          'Select Voucher / Promo Code ...': 'Pilih Baucar / Kod Promosi ...',
          'Session': 'Sesi',
          'Specimen Type': 'Jenis Spesimen',
          'Self-Test Kits': 'Kit Ujian Kendiri',
          'Skip AI verification': 'Langkau pengesahan AI',
          'Statistic': 'Statistik',
          'Shipping Address: ': 'Alamat Dihantar: ',
          'Street 1': 'Jalan 1',
          'Street 2': 'Jalan 2',
          'Share Referral Code Now': 'Kongsi Kod Rujukan',
          'Specimen Type : ': 'Jenis Spesimen: ',
          'Submit Test': 'Hantar Ujian',
          'State': 'Negeri',
          'States: ': 'Negeri: ',
          'Session: ': 'Sesi: ',
          'SUBMIT RESULT': 'HANTAR HASIL',
          'Submit to MySejahtera': 'Hantar ke MySejahtera',
          'Submit to PERKESO': 'Hantar ke PERKESO',
          'Submit your test result': 'Hantar hasil ujian anda',
          'Shipping Details': 'Maklumat Penghantaran',
          'Shipping': 'Penghantaran',
          'Select Type Of Test': 'Pilih Jenis Ujian',
          'Select Self Test Brand': 'Pilih Jenama Ujian Kendiri',
          'Self-Test Video': 'Video Ujian Kendiri',
          'Scan a valid QR code to get Validation Report':
              'Imbas kod QR yang sah untuk menerima Laporan Pengesahan',
          'Select Point of Care': 'Pilih Panel Klinik',
          'Start Recording Self-Test Video': 'Mula Rekod Video Ujian Kendiri',
          'Treat your friend a trial voucher appointment for their first time register using your code!':
              'Jemput kawan anda dengan baucar untuk pendaftaran kali pertama menggunakan kod anda.',
          'Transfer Amount : ': 'Jumlah Pindahan',
          'Type : ': 'Jenis: ',
          'Type': 'Jenis',
          'Total : ': 'Jumlah : ',
          'Total Payment': 'Jumlah Bayaran',
          'Total Price': 'Jumlah Harga',
          'Test Location : ': 'Test Location : ',
          'Total Payment : ': 'Jumlah Bayaran : ',
          'Test': 'Ujian',
          "The result is 'Invalid'": "Hasil ujian adlaah 'Invalid'",
          'TEST IMAGE :': 'GAMBAR UJIAN :',
          'TRANSFER TO:': 'PINDAH KE:',
          'Type of Appointment': 'Jenis Appointment',
          'Type Of Report: ': 'Jenis Laporan: ',
          'Test Method:': 'Kaedah Ujian:',
          'Transfer Details': 'Perincian',
          'Update Profile': 'Kemas Profil',
          'Unlink from this company?': 'Unlink dari syarikat ini?',
          'Upload Result Image': 'Muat Naik Gambar Hasil',
          'Upload Result Image & Video': 'Muat Naik Gambar & Video Hasil Ujian',
          'Upload Result': 'Muat Naik Hasil',
          'Upload Video': 'Muat Naik Video',
          'Verified': 'Pengesahan',
          'Verify Identification': 'Verifikasi Pengenalan',
          'Validated date: ': 'Tarikh disahkan: ',
          'Validation : ': 'Pengesahan : ',
          'Validation Method': 'Kaedah Pengesahan',
          'Voucher': 'Baucar',
          'Verify Phone Number': 'Sahkan Nombor Telefon',
          'Verify Email': 'Sahkan Emel',
          'Email': 'E-mel',
          'Your Tdlabs ID': 'ID Tdlabs Anda',
          'Your test location': 'Tempat ujian anda',
          'Yes, the result is Negative': 'Ya, hasil ujian adalah Negative',
          'Yes, the result is Positive': 'Ya, hasil ujian adalah Positive',
          "Yes, the result is 'Invalid'": "Ya, hasil ujian adalah 'Invalid'",
          'Step 1': 'Langkah 1',
          'Step 2': 'Langkah 2',
          'Step 3': 'Langkah 3',
          'Step 4': 'Langkah 4',
          'Step 5': 'Langkah 5',
          'Step 6': 'Langkah 6',
          'Scan Qr Code\nEnsure that QR Code is in designated area':
              'Imbas Kod QR\nPastikan Kod QR dalam ruang sepatutnya',
          'Start recording by pressing the image':
              'Mula merakam video ujian kendiri',
          'Select your Point of Care for Self-Test': 'Pilih Tempat Penjagaan',
          'Next': 'Sambung',
          '1. Please place the camera 1 meter away then start recording Self-Test Video':
              '1. Sila letakkan kamera sejauh 1 meter kemudian mula merakam Video Ujian Kendiri',
          '2. Please do not close the APP or press Back button (Continue after 15 mins)':
              '2. Jangan tutup APP atau tekan butang Kembali (Teruskan selepas 15 minit)',
          'Record RTK Antigen Self-Test Process':
              'Rekod Proses Ujian Kendiri Antigen RTK',
          'Ensure that you and the test kit are clearly visible and Follow instructions for self-test kit process':
              'Pastikan anda dan kit ujian kelihatan jelas dan Ikut arahan untuk proses kit ujian kendiri',
          'Ensure that you and your device are 1 Meter Apart before recording':
              'Pastikan anda dan telefon bimbit anda berjarak 1 Meter sebelum merakam',
          'Wait for 15 minutes for the results to show':
              'Sila tunggu 15 minit untuk keputusan anda',
          'Select your Panel Clinics for Self-Test : ':
              'Pilih panel klinik untuk Self Test : ',
          'Reminder': 'Peringatan',
          'Dependency': 'Tanggungan',
          'Add Dependant': 'Tambah Tanggungan',
          'Edit Dependant': 'Edit Tanggungan',
          'My Dependants': 'Tanggungan Saya',
          'Dependant': 'Tanggungan',
          'Age': 'Umur',
          'Relation : ': 'Hubungan : ',
          'Relation': 'Hubungan',
          'Save': 'Simpan',
          'Update': 'Kemaskini',
          'Delete': 'Padam',
          'Retype Email': 'Taip Semula Emel',
          'Retype Phone Number': 'Taip Semula No. Telefon',
          'Phone Number': 'No. Telefon',
          'Corporate Link': 'Link Korporat',
          'Link': 'Pautan',
          'Linked': 'Dipautkan',
          'when you invite your friend using your referral code!':
              'Terima komisen dengan menjemput kawan anda menggunakan kod rujukan!',
          'Please take the test\nand wait for the result to show':
              'Sila ambil ujian\n dan tunggu keputusan ',
          'Saliva': 'Air Liur',
          'AI is verifying...': 'AI Mengesahkan...',
          'Flashlight': 'Lampu Suluh',
          'Please Record For 1 Minute to Proceed':
              'Rakam 1 min sebelum teruskan',
          'Please ensure that all steps are taken':
              'Pastikan semua langkah diikuti',
          'Continue with current recorded self-test video':
              'Teruskan dengan video ujian kendiri terkini',
          'Has the result shown': 'Keputusan telah keluar',
          'Point of Care Selection': 'Pilihan Klinik Panel',
          'Bank transfer': 'Pindahan Bank',
          'Proceed': 'Teruskan',
          'Transfer details': 'Maklumat Pindahan',
          'SubTotal': 'Jumlah',
          'Subtotal': 'Jumlah',
          'Total: RM': 'Jumlah: RM',
          'By continuing, you cannot undo the action, the dependent will be permanently  deleted':
              'Jika diteruskan, tanggungan anda akan kekal dipadamkan',
          'Join Now': 'Sertai Sekarang',
          'Verifying': 'Mengesahkan',
          'Pending Submission': 'Kelulusan Diproses',
          'SIMKA Report': 'Laporan SIMKA',
          'General Report': 'Laporan Am',
          'General Validation (TD)': 'Pengesahan Am',
          'Parents / Parents-in-law': 'Ibu Bapa / Mertua',
          'GrandParents': 'Datuk/Nenek',
          'Guardian': 'Penjaga',
          'Spouse': 'Pasangan',
          'Siblings': 'Adik-beradik',
          'Child': 'Anak',
          'Others': 'Lain-lain',
          'Bank Transfer': 'Pemindahan Bank',
          'Submitted': 'Diserahkan',
          'Paid': 'Dibayar',
          'Processed': 'Telah di proses',
          'Shipped': 'Dihantar',
          'Cancelled': 'Dibatalkan',
          'Void': 'Batal',
          'Positive': 'Positif',
          'Negative': 'Negatif',
          'Need Confirmation': 'Perlukan Pengesahan',
          'Learn More': 'Ketahui Lebih Lanjut',
          'Membership': 'Keahlian',
          'Nasal': 'Hidung',
          'Male': 'Lelaki',
          'Female': 'Perempuan',
          'SIMKA(Fees Apply)': 'SIMKA(Caj Dikenakan)',
          'Hospital/Clinic': 'Hospital/Klinik',
          'Online': 'Atas Talian',
          'Pharmacy': 'Farmasi',
          'Corporate': 'Syarikat',
          'Chain-Store': 'Rangkaian Kedai',
          'Done': 'Selesai',
          'All': 'Semua',
          'Has the result shown?': 'Adakah keputusan telah keluar?',
          'Scan QR / Barcode': 'Imbas QR/Kod',
          'Skip': 'Langkau',
          'Dependant(Optional)': 'Tanggungan(Tidak Wajib)',
          'MY TEST LOCATION': 'Lokasi Ujian Saya',
          'Redemption': 'Penebusan',
          'Email cannot be blank': 'Sila isi Emel',
          'Failed to submit, Please try again.': 'Gagal, Sila cuba lagi.',
          'Please upload your self-test kit video': 'Sila muat naik video anda',
          'No dependants found,\nPlease add or refresh list':
              'Tiada tanggungan ditemui,\nSila tambah atau muat semula senarai',
          'Welcome,': 'Selamat Datang,',
          'since your last screening': 'sejak pemeriksaan terakhir anda',
          'Daily Reward': 'Ganjaran Harian',
          'Daily Rewards': 'Ganjaran Harian',
          'Log in': 'Log masuk',
          'TAC Number': 'Nombor TAC',
          'Register': 'Daftar',
          'Covid Info': 'Info  Covid',
          'Discovery': 'Penemuan',
          'Claim': 'Tuntut',
          'Me': 'Saya',
          'Last Tested:': 'Ujian Terakhir:',
          'Test Select': 'Plih Ujian',
          'Please make sure the result is clearly seen before submitting your result.':
              'Sila pastikan keputusan dilihat dengan jelas sebelum menyerahkan keputusan anda.',
          'Self-Test': 'Ujian Kendiri',
          'Please take the picture with good lighting condition, and place the test-kit within the box provided.\n':
              'Sila ambil gambar dengan keadaan pencahayaan yang baik dan letakkan kit ujian dalam kotak yang disediakan.\n',
          'Please Take the Test and \nWrite TAC Number on Test-Kit':
              'Sila Ambil Ujian dan \nTulis Nombor TAC pada Test-Kit',
          'DETAILS': 'BUTIRAN',
          'Redeem available rewards now!':
              'Tebus ganjaran yang tersedia sekarang!',
          'E-booking': 'E-booking',
          'Ask Doctor': 'Tanya Doktor',
          'Refer & Earn': 'Rujuk & Dapat',
          'TD Mall': 'TD Mall',
          ' Days': ' Hari',
          'Dependants': 'Tanggungan',
          'Demo': 'Demo',
          'Help Desk': 'Bantuan',
          'More': 'Lebih',
          'Change ID': 'Tukar ID',
          'Language': 'Bahasa',
          'Smart Consuming': 'Pengambilan Bijak',
          'Credit Reward Available : ': 'Ganjaran Kredit Tersedia: ',
          'Subscribe to our packages to gain rewards':
              'Langgan pakej kami untuk mendapatkan ganjaran',
          'Come back tomorrow for more': 'Kembali esok untuk maklumat lanjut',
          'Tap to redeem now!': 'Ketik untuk menebus sekarang!',
          'Redeem History': 'Sejarah Tebusan',
          'Purchase History': 'Sejarah Pembelian',
          'Redeem': 'Tebus',
          'Package': 'Pakej',
          'Continue Payment To Proceed': 'Continue Payment To Proceed',
          'Result': 'Hasil',
          'Date Collected: ': 'Tarikh Dikumpul: ',
          'Amount Collected: ': 'Jumlah Dikumpul: ',
          'Home': 'Utama',
          'Self-Test Brand': 'Jenama Ujian-Kendiri',
          'Buy & Earn': 'Beli & Peroleh',
          'Promotions': 'Promosi',
          'Premium': 'Premium',
          'Self-Test Kit': 'Kit Ujian-Kendiri',
          'Buy Package': 'Beli Pakej',
          'Purchases': 'Belian',
          'Total: RM ': 'Jumlah: RM',
          'Need help?': 'Pertolongan?',
          'Forgot your password?': 'Lupa password?',
          'Password': 'Password',
          'Bank ': 'Bank',
          'Delivery Method': 'Kaedah Penghantaran',
          'Delivery': 'Penghantaran',
          'Vending Machine Coming Soon': 'Mesin Layan Diri Akan Datang',
          'User Registration': 'Daftaran Pengguna',
          'Confirm Password': 'Sahkan Kata Laluan',
          'Please confirm your password': 'Sila sahkan kata laluan anda',
          'Referrer ID': 'ID Perujuk',
          'I agree to the ': 'saya setuju dengan',
          'Terms & Conditions.': 'Terma & Syarat.',
          'Sign Up': 'Daftar',
          'Verify PIN': 'Sahkan PIN',
          'Report Us': 'Laporkan Kami',
          'Didnt get your sms?': 'Tidak terima sms anda?',
          'Resend': 'Hantar semula',
          'Resend is available in ': 'Hantar semula tersedia dalam',
          'Verify by email': 'Sahkan melalui e-mel',
          'By verifying using email, you can only login using email':
              'Dengan mengesahkan menggunakan e-mel, anda hanya boleh log masuk menggunakan e-mel',
          'Optional': 'Tidak Wajib',
          'Request By Email': 'Permintaan Melalui E-mel',
          'Password Reset Request': 'Permintaan Tetapan Semula Kata Laluan',
          'View': 'Lihat',
          'Download': 'Muat turun',
          'Record created.': 'Rekod dibuat.',
          'E-Booking': 'E-Tempahan',
          'When did your last period start?': 'Bilakah kali terakhir anda haid?',
          'How long is your menstrual cycle?': 'Berapa lama kitaran haid anda?',
          'How many days did your period last?': 'Berapa lama tempoh haid anda?',
          'Start Tracking': 'Mulakan Kiraan',
          'Period': 'Haid',
          'Ovulation': 'Ovulasi',
          'Days to Next Period': 'Hari untuk haid berikutnya',
          'Days to Next Ovulation': 'Hari untuk ovulasi berikutnya',
          'Edit Cycle': 'Tukar Kiraan',
          'End': 'Akhir',
          'Start': 'Mula',
          'Appointment': 'Temu Janji',
            'Traveller Program': 'Program Pengembara',
          'TRAVELLER PROGRAM': 'PROGRAM PENGEMBARA',
          'TRAVELLER PROGRAM 2': 'PROGRAM PENGEMBARA 2',
          'TRAVELLER PROGRAM 3': 'PROGRAM PENGEMBARA 3',
           'Package Option': 'Pilihan Pakej',
          'Book PCR': 'Tempah PCR',
          'Book PCR + Wechat': 'Tempah PCR + Muat Naik ke WeChat',
          'Agent 1 Stop Solution': 'Diuruskan Ejen',
              'Kindly Fill in this Form to Complete the Process': 'Sila Isi Borang ini untuk Melengkapkan Proses',
        },
        'zh_ZH': {
          'About Us': '关于我们',
          'Active': '处理中',
          'Account Holder : ': '账户持有人 : ',
          'Account No : ': '账号 : ',
          'Address : ': '地址 : ',
          'Address': '地址',
          'Apply Promo Code': '应用促销代码',
          'Apply': '套用',
          'Accept': '接受',
          'Appointment Date : ': '约定日期 : ',
          'Appointment Date: ': '约定日期: ',
          'Appointment Date': '约定日期',
          'Appointment By : ': '预约人 : ',
          'Appointment By: ': '预约人: ',
          'Appointment By': '预约人:',
          'Answer': '回答',
          'Alert': '警报',
          'after you invite your friend using your referral code!':
              '在您使用您的推荐码邀请您的朋友之后！',
          'After the payment is successful, please send the payment proof by: ':
              '支付成功后，请将支付凭证发送至: ',
          'Add Test': '添加测试',
          'Birthday': '生日',
          'BILLING TO:': '计费至:',
          'By continuing, you cannot undo the action, the account will permanently deleted after approval from Tdlabs.':
              '继续操作无法撤消操作，该账户将在获得批准后永久删除 Tdlabs.',
          'City': '城市',
          'Completed': '完成',
          'Confirm Decline Invitation?': '确认拒绝邀请?',
          'Country': '国家',
          'Contact Us': '联系我们',
          'Contact': '联系电话',
          'Change': '改变',
          'Change To Email': '更改为电子邮件',
          'Change To Phone': '换手机',
          'Change Tdlabs ID': '更换 Tdlabs 账号',
          'Cancel': '取消',
          'Click Here To Watch Instruction Video': '点击这里观看教学视频',
          'Click here to view on map': '点击这里在地图上查看',
          'Confirm': '确认',
          'Checkout': '结账',
          'Checkout Confirmation': '结帐确认',
          'Checkout Summary': '结帐摘要',
          'Current Details': '当前信息详情',
          'Current action cannot be revert.': '当前操作无法还原.',
          'Click here to submit your test result': '点击这里提交您的测试结果',
          "Confirm submit the test result? Please recheck again before submit.":
              "确认提交测试结果？请在提交前再次检查.",
          'Confirm Submit': '确认提交',
          'Current Location': '当前地址',
          'Continue': '继续',
          'Check the "DETAILS" section to make sure all the details are correct. ':
              '检查“详细信息”部分以确保所有详细信息都正确. ',
          'Choose your language': '选择你的语言',
          'Choose Your Validation': '选择您的验证方式',
          'Choose Available Voucher': '选择可用优惠券',
          'Change Password': '更改密码',
          'Current Address': '目前的地址',
          'Current Home Address': '当前家庭住址',
          'Change Language': '更换语言',
          'My Surveillance Status': '我的监测状态',
          'Date: ': '日期: ',
          'Date : ': '日期: ',
          'Date': '日期',
          'Dependency': '家属',
          "Didn't get your PIN? ": "没有收到您的 PIN 码？ ",
          'Decline': '衰退',
          'Discount': '折扣',
          'Done': '完成',
          'Description': '描述',
          'DETAILS: ': '细节: ',
          'Enter Promo Code': '输入促销代码',
          'Empty list, pull to refresh.': '空列表，拉动刷新.',
          'Earn Commission': '赚取奖励',
          'Enter New Tdlabs ID': '输入新 Tdlabs 账号',
          'Membership': '会员',
          'Pending': '待办',
          'Join Now': '会员',
          'Select Provider': '选择咨询服务',
          'Free Consultation': '免费咨询',
          'IC/ Passport': '身份证/护照 号码',
          'Retype Email': '重新输入邮箱',
          'General Validation(Free)': '官方验证（免费)',
          'General Validation (TD)': '官方验证',
          'Gender': '性别',
          'History': '历史记录',
          'Helpdesk': '帮助台',
          'Hello,': '您好',
          'Has the result shown?': '是否已显示结果',
          'have invited you.': '邀请了你.',
          'Invite Code: ': '邀请代码: ',
          'Item': '物品',
          'Info-IdChange': '这是您的登录 ID，通过更改您的 Tdlabs ID，您的登录 ID 也会更改.',
          'Instructions': '指示',
          'INSTRUCTIONS :': '指示 :',
          'info-sample-before-test': '请在提交检测结果之前确保结果的画面清晰.',
          'info-sample': '请在光线良好的情况下拍照，并将试剂盒放入提供的盒子内。\n',
          'Logout': '登出',
          'Corporate Link': '企业链接',
          'Link-info': '链接功能将您与公司账号进行连接以便您的公司可以为您安排测试。立即开始与您的公司建立联系!',
          'Latest News': '最新消息',
          'Last Update : ': '最近更新 :  ',
          'linked with company': '与公司挂钩',
          'My Surveillance History': '我的监测历史',
          'Message': '信息',
          'My new ID is an Email': '我的新用户账号是电子邮箱',
          'My new ID is a phone number': '我的新用户账号是手机号码',
          'Nasal': '鼻腔',
          'Name': '名称',
          'Name : ': '名称 : ',
          'No': '否',
          'No, the result is Negative': '不，结果是否定的',
          'No result found.': '没有找到结果.',
          'No result found, pull to refresh.': '未找到结果，拉动刷新.',
          'Nationality': '国籍',
          'Order History': '订单历史',
          'Our AI system detect the result as ': '我们的人工智能系统检测结果为 ',
          ' Pages': '页',
          ' of ': ' 第- ',
          'Clinics]': ' 个地点]',
          'Phone Number': '手机号码',
          'Phone No. : ': '电话号码: ',
          'Phone No.': '电话号码',
          'Postcode': '邮政编码',
          'Profile': '个人信息',
          'Payment': '支付',
          'Policy': '政策',
          'Privacy Policy': '隐私政策',
          'Price': '价格',
          'Price:': '价格:',
          'Please complete your profile to proceed': '请填写您的个​​人资料以继续',
          'Pay using bank transfer method to the account number listed in "TRANSFER TO" section with exact transfer details as shown.':
              '使用银行转账方式向“转账至”部分中列出的帐号支付准确的转账详情，如图所示.',
          'Point of care : ': '指定诊所 : ',
          'Point of Care: ': '指定诊所: ',
          'Point of Care': '指定诊所',
          'Point Of Care Selection': '自检护理站点选择',
          'Point of care ': '指定诊所 ',
          'Please take the picture with good lighting condition':
              '请在光线充足的情况下拍照',
          'Please key in the 6 digit PIN sent to your': '请输入发送给您的 6 位 PIN 码',
          'Please take the test\nand wait for the result to show':
              '请进行测试并等待结果显示',
          'Please confirm the result.': '请确认结果.',
          'Please upload your IC/Passport photo for verification purposes, your IC/Passport must be shown clearly in the photo':
              '请上传您的身份证/护照照片以供验证，您的身份证/护照必须清楚地显示在照片中',
          'QR Scan': '二维码扫描',
          'Shipping & Refund Policy': '运输和退款政策',
          'Start Recording Self-Test Video': '开始录制自检视频',
          'skip-ai-info': '我们的 AI 系统似乎很难检测到您的自检套件结果，请跳过 AI 进行手动验证?',
          '1. Please place the camera 1 meter away then start recording Self-Test Video':
              '录制前请确保您与相机设备相距 1 米',
          '2. Please do not close the APP or press Back button (Continue after 15 mins)':
              '请勿关闭应用程序或按返回按钮(15 分钟后继续）',
          'Please wait for': '请等待',
          'Ai result not found\nPlease retake picture': 'AI 结果无法显示 请重新拍照',
          'Result Confirmation': '结果确认',
          'Request Delete Account': '请求删除帐户',
          'Reference No: ': '参考编号: ',
          'RESULT DETAILS :': '结果详情 :',
          'registered mobile phone no.': '注册手机号.',
          'registered email': '注册的电子邮件',
          'Save': '保存',
          'Skip': '跳过',
          'Saliva': '唾液',
          'Self Test': '自我测试',
          'Self-Test Video': '自检视频',
          'Self-Test Kit Obtained From': '自检试剂盒获得自',
          'Submit': '提交',
          'SIMKA(Fees Apply)': 'SIMKA(付费）',
          'Step 1': '步骤一',
          'Step 2': '步骤二',
          'Step 3': '步骤三',
          'Step 4': '步骤四',
          'Step 5': '步骤五',
          'Step 6': '步骤六',
          'Scan Qr Code\nEnsure that QR Code is in designated area':
              '扫描二维码并确保二维码在指定区域',
          'Start recording by pressing the image': '按下图像开始录制',
          'Select your Point of Care for Self-Test': '选择您的指定诊所',
          'Next': '下一页',
          'SubTotal': '付款总额',
          'Subtotal': '订单总额',
          'Statistic': '数据统计',
          'Record RTK Antigen Self-Test Process': '录制 RTK 抗原体自检过程',
          'Ensure that you and the test kit are clearly visible and follow instructions for self-test kit process':
              '请确保您与测试套件都清晰可见，并遵循自\n测过程的说明',
          'Ensure that you and your device are 1 Meter Apart before recording':
              '录制前请确保您与设备相距 1 米',
          'Wait for 15 minutes for the results to show': '等待 15 分钟以显示结果',
          'Select your Panel Clinics for Self-Test : ': '选择您的指定诊所 : ',
          'Submit Test': '提交测试',
          'Submit to MySejahtera : ': '提交到 MySejahtera : ',
          'Submitted date: ': '提交日期: ',
          'Referral': '推荐',
          'Reminder': '提醒',
          'Proceed with payment': '继续付款',
          'Session': '时间段',
          'Session: ': '时间段',
          'Session : ': '时间段 : ',
          'Free': '免费',
          'Select Date': '选择日期',
          'Self-Test Kits': '自检套件',
          'Capture picture of test kit and upload result \nPlease ensure that the result image is clear before submitting':
              '拍摄测试套件的图片并上传结果\n提交前请确保结果图片清晰',
          'Street 1': '街道 1',
          'Street 2': '街道 2',
          'Select Voucher / Promo Code ...': '选择优惠券/促销代码...',
          'Scan a valid QR code to get Validation Report': '扫描有效二维码获取验证报告',
          'Specimen Type': '样本类型 : ',
          'Share Referral Code Now': '立即分享推荐代码',
          'Treat your friend a trial voucher appointment for their first time register using your code':
              '赶快召集朋友们来领取首次登录优惠吧！',
          'Invite your friend using your referral code and earn your rewards now':
              '立即使用您的推荐码来邀请朋友以赚取您的奖励',
          'Shipping Details': '邮寄资料',
          'Shipping fees': '运费',
          'Shipping': '运费',
          'Contact: ': '联系电话: ',
          'Proceed: ': '继续: ',
          'Submit your test result': '提交您的测试结果',
          'States: ': '状态: ',
          'State': '州属: ',
          'Select Type of Test': '选择测试类型',
          'Select Self Test Brand': '选择自测品牌',
          'Select Point of Care': '选择指定诊所',
          'Treat your friend a trial voucher appointment for their first time register using your code!':
              '赶快召集朋友们来领取首次登录优惠吧！',
          'Type : ': '类型  : ',
          'Test Location : ': '测试地点 : ',
          'Location : ': '测试地点 : ',
          'Type': '类型',
          'Test': '测试',
          "The result is 'Invalid'": "结果是'无效'",
          'Total Payment': '付款总额',
          'Total Price': '总价',
          'Type of Appointment:': '预约类型',
          'Transfer Amount : ': '转账金额 : ',
          'TEST IMAGE :': '测试图像 :',
          'Test Method:': '测试方法:',
          'Type Of Report: ': '报告类型: ',
          'TRANSFER TO:': '转移至:',
          'Transfer Details': '报告细节 : ',
          'Update Profile': '更新个人信息',
          'Upload Result': '上传结果图片',
          'Upload Result Image': '上传结果图片',
          'Unlink from this company?': '取消与这家公司的联系?',
          'Verify Identification': '验证身份',
          'Validated date: ': '验证日期: ',
          'Validation Method': '验证方法',
          'Validation : ': '验证 : ',
          'Voucher': '优惠券',
          'Verify Phone Number': '验证电话号码',
          'Verify Email': '验证邮件',
          'We will proceed automatically': '我们将会自动前进 : ',
          'Your Tdlabs ID': 'Tdlabs ID',
          'Your test location': '你的检测地点',
          'Yes': '是',
          'Yes, the result is Negative': '是的，结果是否定的',
          'Yes, the result is Positive': '是的，结果是肯定的',
          "Yes, the result is 'Invalid'": "是的，结果是“无效”'",
          'Simple Chinese': '简体中文',
          'Email': '电子邮件',
          'Verified': '验证',
          'Current Password': '当前密码',
          'New Password': '新密码',
          'Add': '添加',
          'Add Dependant': '添加家属',
          'Edit Dependant': '编辑家属',
          'My Dependants': '我的家属',
          'Dependant': '我的家属',
          'Age': '年龄',
          'Relation : ': '关系 : ',
          'Relation': '关系',
          'Update': '更新',
          'Delete': '删除',
          'Retype Phone Number': '重新输入电话号码',
          'Link': '企业链接',
          'Linked': '已链接',
          'when you invite your friend using your referral code!':
              '立即向您的朋友发送推荐代码的邀请以赚取您的奖励！',
          'AI is verifying...': 'AI 正在进行验证',
          'Flashlight': '闪光灯',
          'Please Record For 1 Minute to Proceed': '请录制 1 分钟以继续',
          'Please ensure that all steps are taken': '请确保已采取所有步骤',
          'Continue with the current recorded self-test video?': '继续当前录制的自检视频',
          'IC / Passport': '身份证/护照 号码',
          'Point of Care Selection': '指定诊所选择',
          'Bank transfer': '银行转账',
          'Proceed': '继续',
          'Transfer details': '转账详情',
          'Info': '资讯',
          'Dependency ': '家属',
          'Parents / Parents-in-law': '父母/岳父母',
          'GrandParents': '祖父母',
          'Guardian': '监护人',
          'Spouse': '伴侣',
          'Siblings': '兄弟姐妹',
          'Child': '孩子',
          'Others': '其他',
          'Scan QR / Barcode': '扫描二维码/条码',
          'All': '全部',
          'General Report': '报告',
          'Hospital/Clinic': '医院/诊所',
          'Online': '线上',
          'Pharmacy': '药房',
          'Corporate': '公司',
          'Chain-Store': '连锁店',
          'Ai Result Confirmation': 'AI 结果确认',
          'Skip AI verification': '跳过 AI 验证',
          'Positive': '阳性',
          'Negative': '阴性',
          'Invalid': '无效',
          'Details': '报告细节',
          'Bank Transfer': '银行转账',
          'Verifying': '验证',
          'Pending Submission': '待提交',
          'SIMKA Report': 'SIMKA 报告',
          'SIMKA': '专业验证',
          'eGHL Payment Gateway': 'eGHL 支付通道',
          'I hereby confirm that this Self Test was conducted according to procedures stated in this app and the sample is authentically my own':
              '我在此确认此自检结果是属于我本人的，并且已遵照应用程序中所述的程序来进行测试',
          'Corporate-': '公司-',
          'm s': '分钟 秒',
          'Payment Gateway': '支付通道',
          'Time Remaining': '剩余时间',
          'Payment ID': '付款编号',
          'Payment for': '付款',
          'Total': '总额',
          'Other Payment Method ': '其他付款方式',
          'Online banking': '线上支付',
          'Ewallet': '电子钱包',
          'By summitting the payment, you hereby agree to eGHL PDPA Policy':
              '您确认付款即表示您同意 eGHL PDPA 的政策',
          'Cancel and Return to TDLabs': '取消并返回 TDLabs',
          'Secured Payments Powered by': '安全支付',
          'Dependant(Optional)': '家属 (自选)',
          'Redemption': '兑换',
          'Points': '积分',
          'No dependants found,\nPlease add or refresh list':
              '未找到家属,\n请添加或刷新列表',
          'By continuing, you cannot undo the action, the dependent will be permanently deleted':
              '点击继续后，您将无法撤销行动，家属将被永久删除',
          'Please input ': '请输入 ',
          ' name': ' 名称',
          'Payment Pending': '待付款',
          'Search': '搜索',
          'Email cannot be blank': '电子邮件不能为空',
          'Failed to submit, Please try again.': '提交失败，请再次尝试',
          'Please upload your self-test kit video': '‘请上传您的自我检测视频',
          'Welcome,': '欢迎,',
          'since your last screening': '距离您上一次检测',
          'Daily Rewards': '每日奖励',
          'Daily Reward': '每日奖励',
          'Log in': '登入',
          'TAC Number': '验证码',
          'Register': '注册',
          'Covid Info': '新冠肺炎资讯',
          'Discovery': '发现',
          'Claim': '索取',
          'Me': '我',
          'Last Tested:': '最近测试:',
          'Test Select': '测试选择',
          'Please make sure the result is clearly seen before submitting your result.':
              '在提交结果前，请确保结果清晰',
          'Self-Test': '自我检测',
          'Please take the picture with good lighting condition, and place the test-kit within the box provided.\n':
              '请在阳光充足的情况下进行拍摄，并将抗原试纸放入所提供的盒子内\n',
          'Please Take the Test and \nWrite TAC Number on Test-Kit':
              '请开始测试并把验证码写在抗原试纸上',
          'DETAILS': '详情',
          'Redeem available rewards now!': '立即兑换可用奖励',
          'E-booking': '线上预定',
          'Ask Doctor': '咨询医生',
          'Refer & Earn': '推荐 & 赚取',
          'TD Mall': 'TD商城',
          'Dependants': '家属',
          'Dependant(Optional): ': '亲属（如有): ',
          'Demo': '演示',
          'Help Desk': '联系客服',
          'More': '更多',
          'Call': '联系客服',
          'Change ID': '更改ID',
          'Language': '语言',
          'Smart Consuming': '最佳选择',
          'Reward Available : ': '有效积分: ',
          'Subscribe to our packages to gain rewards': '订阅我们的配套以获取奖励',
          'Come back tomorrow for more': '明天再来以知更多',
          'Tap to redeem now!': '点击立即兑换',
          'Redeem History': '兑换记录',
          'Purchase History': '购买记录',
          'Redeem': '兑换',
          'Package': '配套',
          'Continue Payment To Proceed': '结账',
          'Result': '结果',
          'Date Collected: ': '订单日期: ',
          'Amount Collected: ': '订单总额’: ',
          'Home': '主页',
          'Self-Test Brand': '自测品牌',
          'Buy & Earn': '购买 & 赚取',
          'Promotions': '折扣',
          'Premium': '升级会员',
          'Self-Test Kit': '抗原试纸',
          'Buy Package': '购买配套',
          'Purchases': '购买',
          'SUBMIT RESULT': '提交结果',
          'MY TEST LOCATION': '我的检测地点',
          'Total: RM ': '付款总额: RM',
          'Order Item(s): ': '购买物品:',
          'Payment By: ': '付款方式:',
          'PAYMENT DETAILS: ': '付款详情: ',
          'Need help?': '需要帮助?',
          'Forgot your password?': '忘记密码?',
          'Password': '密码',
          'Bank ': '银行',
          'Delivery Method': '配送方式',
          'Delivery': '邮寄',
          'Vending Machine Coming Soon': '即将推出自动贩卖机',
          'User Registration': '用户注册',
          'Confirm Password': '确认密码',
          'Please confirm your password': '请确认您的的密码',
          'Referrer ID': '推荐人ID',
          'I agree to the ': '我同意',
          'Terms & Conditions.': '条款与条件',
          'Sign Up': '注册',
          'Verify PIN': '验证PIN码',
          'Report Us': '提交问题',
          'Didnt get your sms?': '没有收到',
          'Resend': '重发',
          'Resend is available in ': '秒后可重新发送',
          'Verify by email': '通过电子邮件验证',
          'By verifying using email, you can only login using email':
              '当使用电子邮件进行验证，您只能使用电子邮箱登入',
          'Optional': '可选  ',
          'Request By Email': '重置通过电子邮件',
          'Password Reset Request': '密码重置请求',
          'View': '查看',
          'Download': '下载',
          'Record created.': '记录已创建',
          'E-Booking': '线上预约',
          //added by 30112022
          'Home page': '主页',
          'Medical': '医疗',
          'Rewards': '奖励',
          'Smart Programme': '精明消费计划',
          'Smart Keluarga': 'Smart Keluarga\n智能药柜',
          'More page': '更多页面',
          'TD Consult\n(Coming Soon)': 'TD咨询\n(即将推出)',
          'MYCSR\n(Coming Soon)': '社会责任计\n（即将推出)',
          'Cart icon': '购物车图标',
          'Cart': '购物车',
          'Vending Machine': '贩卖机',
          'Mall': '商城',
          'Empty list,pull to refresh': '空列表，拉动刷新',
          'Smart Consuming Programme': '精明消费计划',
          'Proof of Test': '检测证明',
          'Covid-19 Screening': '新冠病毒检测',
          'Ask Doctor(Coming Soon)': '医疗咨询（即将推出)',
          'Ask Doctor\n(Coming Soon)': '医疗咨询（即将推出)',
          'Ask Doctor (Coming Soon)': '医疗咨询（即将推出)',
          'Period Tracker': '生理期追踪',
          'Health Ledger': '健康账本',
          'Medical Directory': '指南',
          'Directory': '指南',
          'Categories': '类别',
          'Clinics': '地点',
          'Cardiology (Heart Specialist)': '心脏科',
          'Chiropractic (Spine Specialist)': '脊骨神经科',
          'Confinement Center': '月子中心',
          'Dermatology (Skin Specialist)': '皮肤科',
          'Fertility Clinics': '助孕诊所',
          'Gastroenterology Hepatology (Digestive Sys. Spec)': '肠胃肝脏科',
          'General Practitioner': '全科医疗诊所',
          'Haemodialysis Center (Blood Dialysis)': '洗肾中心',
          'Health Screening': '健康检测中心',
          'Maxillofacial (Dental Care)': '牙科',
          'Medical Aesthetic': '医美中心',
          'Obstetrics Gynaecology (Reproductive Specialist)': '妇科',
          'Ophaltomology (Eye Specialist)': '眼科',
          'Otorhinolaryngology (Ear, Nose, Throat Specialist)': '耳鼻喉科',
          'Ortopaedic (Bone Specialist)': '骨科',
          'Physiotherapy': '物理治疗中心',
          'Psychiatrist': '心理科',
          'Traditional Chinese Medicine Center': '中医',
          'Wellness Section': '保健中心',
          'Clinic': '诊所',
          'Registration No: ': '注册号',
          'Email: ': '邮箱',
          'Address: ': '地址',
          'Description: ': '详情',
          'Expertise: ': '专科',
          'Directions': '地图',
          'Book Appointment': '联系',
          'Close': '关闭',
          'Covid Screening': '新冠病毒检测',
          'General Validation（Free)': '官方验证（免费)',
          'General Booking': '般预订',
          'Self Test Select': '选择检测',
          'Self Test Result': '检测结果',
          'Brand': '品牌',
          'Clear': '移除',
          'Self Test Scan': '检测扫描',
          'Professional Validation(Fees Apply)': '专业验证（付费)',
          'Swipe to continue': '滑动继续',
          'Record RTK Antigen Self Test Process': '录制自测过程',
          'Ensure that you and the test kit are clearly visible and follow instruction for self test kit process':
              '请确保您和测试套件清晰可见，并按照自测套件流程的说明进行操作',
          'Capture picture of test kit and upload result': '拍摄测试套件的图片并上传结果',
          'Please ensure that the result image is clear before submitting':
              '提交前请确保测试结果图片清晰',
          'Proceed with payment': '继续付款',
          'Self-test report will be sent once ready': '自测报告准备好后将会发送',
          'RT-PCR': '聚合酶链反应 （RT-PCR)',
          'RTK Antigen': 'RTK抗原',
          'Neutralizing Antibody': '中和抗体',
          'Covid-19 Booster Vaccination': '新冠加强疫苗接种',
          'Walk In': '当天步入',
          'Drive-Thru': '快速通车',
          'Select Date': '选择日期',
          'Cancel': '取消',
          'OK': '确认',
          'Morning': '早上',
          'Afternoon': '下午',
          'Evening': '傍晚',
          'Morning (8am - 10am)': '早上 (8am - 10am)',
          'Afternoon (2pm - 4pm)': '下午 (2pm - 4pm)',
          'Evening (6pm - 8pm)': '傍晚 (6pm - 8pm)',
          'Check Out': '登出',
          'Point of Care:': '诊所:',
          'Type:': '类型:',
          'Appointment Date :': '预约日期:',
          'Session:': '时段',
          'Smart Consuming Package': '精明消费计划',
          'Smart Rewards Programme (SRP)': '精明奖励计划',
          'Smart Consuming Programme (SCP)': '精明消费计划',
          'Smart Rewards Programme (SRP)\nSimply by making purchases at our TD Mall or Farmasi Keluarga vending machines and collecting Teda Coins, you can gain fantastic bonuses.\nFor every RM1 spent, you can earn 100 Teda Coins 10,000 points = RM1 worth of Teda Coins \n*T&C Apply':
          '您只需在TD商城或 Smart Keluarga智能药柜贩卖机上进行购物，您就可获得额外Teda Coin奖励',
          'Smart Consumer Programme (SCP)\nGrab product with SCP Program in TD Mall or Vending Machine\nGet 100% Rebate * \nTerms & Conditions Apply*': '赶紧前来选购TD商城或Smart Keluarga智能药柜贩卖机的参与商品吧！购买可获得100%回扣喔！*需符合条规',
          'Proof-Of-Test (POT) Reward': '检测验证奖励',
            '1.Perform Covid-19 Self-Test\n2.Upload  Covid-19 RTK Self-Test Result\n3.Get Reward of 2000 TDC \n4.Spend with your TDC on TDMALL & Farmasi Keluarga !': '进行新冠病毒检测\n1.上传测试结果\n2.获取2000x Teda Coin奖励\n3.在TD商城或智能药柜贩卖机\n4.使用Teda Coin进行购物',
          'Reward': '奖励',
          'Reward Available Today': '今日奖励',
          'Welcome to Smart Keluarga': '欢迎来到 Smart Keluarga 智能药柜',
          '1.Select nearest machine\n2.Select desired item\n3.Check out and Collect':
              '1.选购临近药柜贩卖机\n2.选购心仪商品\n3.登出及取物',
          'Select Vending Machine': '选择贩卖机',
          'Nearest Vending Machine \nbased on your current location':
              '最临近您地点的贩卖机',
          'Beverage & Confectionery': '饮料和糖果',
          "Children's Health": '儿童健康',
          'COVID-19': '新冠病毒',
          'Family Planning': '家庭计划',
          'First Aid & Wound Care': '急救和伤口护理',
          'Nutrition': '营养类',
          'Over the Counter': '非处方药品',
          'Personal Care': '个人护理',
          'Promotion': '优惠',
          'Add to Cart': '添加购物车',
          'Buy Now': '立即购买',
          'Quantity': '数量',
          'Check out': '结账',
          'Check Out Confirmation': '结账信息',
          'Self Pickup': '自取',
          'Standard': '标准',
          'Contact No': '联络电话',
          'Check out information': '结账信息',
          'Product Description': '产品描述',
          'Normal Delivery': '普通运输',
          'App version ': '版本 ',
          'Are you sure you want to exit the app?': '您确定要退出应用程序吗？',
          'Quit': '离开',
          'When did your last period start?': '您的最后一次经期时期?',
          'How long is your menstrual cycle?': '您的月经周期是多久？',
          'How many days did your period last?': '您的经期维持多少天？',
          'Start Tracking': '开始记录',
          'Period': '经期',
          'Ovulation': '排卵期',
          'Days to Next Period': '天 距离下次经期还有',
          'Days to Next Ovulation': '天 距离下次排卵期还有',
          'Edit Cycle': '编辑生理期',
          'End': '结束',
          'Start': '开始',
          'Covid': '新冠病毒检测',
          'Appointment': '预约',
          'Type of Appointment: ': '预约服务类型: ',
          'Traveller Program': '回乡计划',
          'TRAVELLER PROGRAM': '回乡计划',
          "Traveller's Programme": '回乡计划',
          'TRAVELLER PROGRAM 2': '旅游计划 配套2',
          'TRAVELLER PROGRAM 3': '旅游计划 配套3',
          'Book your appointment at point of care, date & session': '在指定护理站点的日期和时段上进行预约',
          'Confirm your check out summary before proceed your payment transfer': '在进行付款转账之前，请确认您的结账信息并完成付款',
          'You will receive a receipt of payment & required fill in your information at the link of Google Form provided': '您将收到付款收据，并需要在提供的 Google 表单链接中填写绿码信息',
           'After all the information have been fill in at Google Form, our customer service will assist to update the result to WeChat mini app program International Version of Epidemic Prevention Health Code': '绿码申请成功后，客服人员将会把您的报告上传至健康账本，您可在健康账本中搜索取得报告',
           'Book your agent before proceed your payment transfer': '在进行付款转账之前，请预约您的代理人员',
           'You will receive receipt of payment & required fill in your information at the link of Google Form provided': '您将收到付款收据，并需要在提供的 Google 表单链接中填写绿码信息',
           'Within 24 hours, the agent will contact and guide you': ' 在24小时内，代理人员将与您联系并指导您',
           'Agent will assist to obtain the report, organize airport transportation and boarding services': '代理人员将会协助您获取报告、安排机场接送及登机等服务',
          'Package Option': '配套选择',
          'Book PCR': '预约PCR核酸检测',
          'Book PCR + Wechat': '预约PCR核算检测 ＋微信绿码更新',
          'Agent 1 Stop Solution': '一站式代理人员服务',
          'Thank you for booking with TD-Labs':
              '感谢您使用TD-Labs应用程序进行预约',
              'Kindly Fill in this Form to Complete the Process': '请填写表单以完成程序',
              'title': '日历',
    'weekdayFormat': '窄',
    'Male': '男',
          'Female': '女',
          //added by 30112022
        },
      };
}
